### ISSUE TITLE
Feature Request: Adding object notes via the API

### ISSUE THREAD

**Issue by phrfpeixoto** [stripe/stripe-python#1003]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

I want to be able to add regular text notes to Stripe objects via the API.

This feature is available on the dashboard, and (as an example) it would be useful for canceling payment intents with a reason other than `duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`

![Screenshot 2023-08-02 at 17 32 32](https://github.com/stripe/stripe-python/assets/10242829/b722878f-daea-4031-8b31-95137ced49df)

### Additional context

It seems the API is already in place for that, but the Python package does not support it:
Inspecting the browser requests, we can clearly see the note being created:
```
curl 'https://dashboard.stripe.com/v1/notes' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \

  REDACTER HEADERS

  --data-raw 'parent=ch_3NXylFEA31HiYedh0Bfpcee5&text=Custom+Reason+added+as+note' \
  --compressed
```

which returns

```json
{
  "id": "note_1NalioEA31Hiasdlkfjw3xDOWc",
  "object": "note",
  "created": 1691008362,
  "created_by": {
    "id": "REDACTED",
    "object": "user",
    "email": "REDACTED",
    "name": "REDACTED",
    "password_set": true
  },
  "edited_by": null,
  "from_email": null,
  "mentions": [],
  "parent": "ch_3NXylFEaw3rsdedh0Bfpcee5",
  "pinned": false,
  "source": "dashboard",
  "text": "Custom Reason added as note"
}
```

**Comment by remi-stripe** [comment]
@phrfpeixoto Github issues are limited to bugs or feature requests with the stripe-python library. Unfortunately, the library doesn't support this because this is not a public API feature and is only supported in the Dashboard.
We don't have plans to ship support for this in the future in the API unfortunately but you can flag your interest directly to our support team: https://support.stripe.com/contact
