### ISSUE TITLE
Need to be able to set billing_cycle_anchor with subscription_update_confirm portal session flow

### ISSUE THREAD

**Issue by maxiedaniels** [stripe/stripe-python#1216]
### Is your feature request related to a problem? Please describe.

For my application, i need to have upgrades occur straight away, with the billing cycle reset to 'now'. I went through the whole process of building out a custom portal configuration for this to use with a subscription_update_confirm flow, but then found out there is no way to adjust billing cycle. I can set proration, which is the other thing i need to set, so that's all good.

### Describe the solution you'd like

There should be some way to adjust billing_cycle_anchor with subscription_update_confirm flow, whether that's directly in the flow settings or within a portal configuration object.

### Describe alternatives you've considered

I know my webhook can adjust the billing anchor, but the problem is that the user will see the wrong dates on the subscription_update_confirm flow page if i do that.

**Comment by remi-stripe** [comment]
@maxiedaniels Github issues are limited to bugs and feature requests with the SDK itself. Your ask is a feature request in the API (which the SDK would automatically support if the API did). You should flag those to our support team so that we can track this as a potential change we could do in the future. You can contact them here: https://support.stripe.com/contact
