### ISSUE TITLE
AttributeError: 'CustomerService' object has no attribute 'modify' with StripeClient

### ISSUE THREAD

**Issue by jvdboog** [stripe/stripe-python#1245]
### Describe the bug

```
stripe_client = StripeClient(api_key=stripe_api_key)
stripe_client.customers.modify(
    id=shopping_stripe_customer_obj.stripe_customer_id,
    email=self.request.user.email,
)
```

results in:

```
AttributeError: 'CustomerService' object has no attribute 'modify'
```

### To Reproduce

1. use stripe_client
2. use the code above
3. get error

### Expected behavior

I would expect the customer to be updated.

### OS

macOS

### Language version

Python 3.11.4

### Library version

stripe = "8.3.0"

### API version

2022-11-15

### Additional context

Not sure about the Stripe API Version. I am using a webhook docker container which says it is using 2022-11-15. But the error is in Python, not the API.

**Comment by remi-stripe** [comment]
@jvdboog if you're using the client/service interface (which just shipped), the method is called `update()` and not `modify()`. The name `modify` was historical due to the way all API resources in Python inherit from Python's `dict` and `update()` was reserved.

When we shipped the client/service approach we moved to `update()` instead. I've updated the [migration guide](https://github.com/stripe/stripe-python/wiki/Migration-guide-for-v8-(StripeClient)) to cover this more clearly.

You code should look like this instead:
```
customer_updated = stripe_client.customers.modify(
  shopping_stripe_customer_obj.stripe_customer_id,
  params={
    "email": self.request.user.email,
  }
)
```
