### ISSUE TITLE
Setting trial_end to None leads to invalid request

### ISSUE THREAD

**Issue by piquadrat** [stripe/stripe-python#193]
Example: https://gist.github.com/piquadrat/0609bb9d6722bf98ff9c

The request sent to the API sets the trial_end to the empty string, which is rejected by the API.

I found this issue due to some code that I wrote that automatically re-sets `trial_end` and `quantity` to their current values when changing the `plan` of a subscription, to ensure they are preserved while changing the plan.

Discussion on IRC: https://botbot.me/freenode/stripe/2015-12-11/?msg=55907957&page=4

**Comment by tetrakai** [comment]
Unfortunately, unsetting the trial_end on a subscription isn't
supported, as it wouldn't be clear whether the existing trial should
have ended in the past or at the moment you made the request.

In your case, it sounds you're creating a new subscription object, so
you should be able to get the desired behavior by only setting trial_end
if the value is not None.

Otherwise, if you're updating an existing subscription, setting the
trial_end to 'now' will cause it to end immediately.
