### ISSUE TITLE
Get a dictionary representation of Stripe objects with only build-in Python types

### ISSUE THREAD

**Issue by vcatalano** [stripe/stripe-python#219]
I'm currently using the `convert_to_stripe_object` in one of my libraries and this allows me convert a Python dictionary of my object to a Stripe object. Is there a way to basically do the reverse of this function in which the resulting object contains only Python built-in types (i.e. dict, list, string, boolean and number)?

In my case, I'm attempting to save a Customer object to a NoSQL database. The database only supports Python built-in types. However, when I attempt to create a create a dictionary from my customer object using `dict(customer_obj)`, the resulting object is not serializable to JSON since it contains lists of Subscription and Card objects. This has ultimately led me to use the following:

```python
    import json
    customer_obj = stripe.Customer.create(...)
    json.dumps(customer_obj, sort_keys=True, indent=2)
    customer_dict = json.loads(customer_json)
```

As you can see, this is not ideal. Is it possible that I'm just missing obvious in my transformation of a Customer object to a dictionary?

**Comment by brandur** [comment]
Hi @vcatalano,

Unfortunately, to my knowledge there's no way of doing exactly what you're trying to do here given the current state of the bindings. They're written to only have to handle deserialization rather than go the other way around.

One thing that's pretty close is that `StripeObject` has a method called `serialize` which is used to turn a new or updated object into parameters to send back up to the API. Before encoding those parameters look like a basic dictionary. I think the only problematic difference compared to what you're trying to do is that `serialize` tries to be smart about things and only includes fields that have changed since the object is loaded.

We could consider adding an optional parameter to `serialize` along the lines of `force=false` that could be used to serialized all fields regardless of whether they're saved or unsaved. I'll doubt we'd tackle that one, but we'd certainly consider a well-tested patch!

**Comment by vcatalano** [comment]
Thanks for the insight, @brandur! It looks like I'll be sticking with my serializing-deserializing solution for the time being.

**Comment by duaneking** [comment]
## Please Reopen This
![please](https://user-images.githubusercontent.com/569341/53853481-769be900-3f7a-11e9-9316-723dc713a17b.gif)

Respectfully, I would like to request that this should be reopened, or even be linked to a new bug filed on the overall architecture of how result objects should be handled in the python library to make it higher quality and provide for the missed opportunities it currently presents.

In short, this python client API did not get the architectural attention it deserved and while its clear the person who did it came from an understanding of interference in OOP it can still be greatly improved.

## The docs are "hand wavy" and punt on actual use of the stripe response result object anyway

There is clearly a deep code quality issue here. It is also a severe code smell from an architectural perspective because the wrong data types are actively being used for many of the calls.

The result object you get back from the Stripe API call from the network is so overloaded on its own that even the publicly available Stripe provided documentation actively goes out of its way to do its best to not even TRY to make use of that result object directly in any way, and instead intentionally and publicly chooses to print the resulting object as raw JSON when the object itself is NOT actually any form of JSON, as shown below and in any python console.

![ohthatsnotgood](https://user-images.githubusercontent.com/569341/53853783-b7e0c880-3f7b-11e9-8063-a6324bc3c71a.gif)


The docs actively misrepresent itself explicitly by explicitly showing json for objects, and implicitly by not providing an explicit way to translate that object to native python types without going the JSON route mentioned above or doing work that should have been done in the library itself.

Worse, the documentation even chooses to show code examples of entirely separate exception cases rather than attempt to deal with extracting real values from the literal result object that is returned by the API call.  It just skips over that part, the most important part.  The code to deal with the response and get meaningful data from it is literally empty in all the examples I can see in the docs as of today, 3/5/2019 @5pm.

In short, the docs are misrepresenting things by omission, using leading language, and actively creating confusion due to the gaps that exist between the JSON representation of the literal objects and the python implementation of the API.

In fact, the docs literally provide no examples of what to do with a StripeObject after its gotten from the network, and actively hide the fact that they are not even full JSON objects by misrepresenting them as JSON objects in the documentation and as full class objects of their own type in the python console output you get when you check this manually, when that is clearly not the case.

As a result, the Python API documentation, while usable, is not meeting the quality bar I would expect from a company that handles money so deeply and claims to be "dev first", as it is sharp around the edges and missing polish while actively missing much needed things like exactly what the OP is asking for and creating a gap.

![bebetterthanthegap](https://user-images.githubusercontent.com/569341/53853882-2887e500-3f7c-11e9-9c1c-acd020f8906c.gif)


## Example of how the API is lacking polish.

Lets explain this with the simplest call of all, a simple "get my balance" call:

![birdatm](https://user-images.githubusercontent.com/569341/53854251-8cf77400-3f7d-11e9-8901-6ef8aba136e2.gif)

```
import stripe
stripe.api_key = <your brand new test account key here>
b = stripe.Balance.retrieve()
print(b)
```
This gets us JSON output in a python console:

```
print(b)
{
  "available": [
    {
      "amount": 0,
      "currency": "usd",
      "source_types": {
        "card": 0
      }
    }
  ],
  "livemode": false,
  "object": "balance",
  "pending": [
    {
      "amount": 0,
      "currency": "usd",
      "source_types": {
        "card": 0
      }
    }
  ]
}
```

So you would think, "Oh, my bad, the response object the stripe docs go out of their way to not touch in any meaningful way is just a JSON formatted string, right?"

Nope.. not at all.  As shown by python itself in the console:

```
>> isinstance(b, (str, bytes))  # Python 3, use (basestring,) for python 2
False
```
So 'b' is not a string or byte iterable and the docs are giving us a translated value of the object after translating the object instance into JSON, and not giving us a literal absolute value of what the object is.  Fine, we are mighty developers, and we can deal with this, it is just one of out only 98 problems (To quote some musical philosophy).

But you still ponder to yourself "What type is it, really? What am I in for here?".

So you ask it in the kindest, most respectful way possible "What should I call you, my new friend?  Right now you are a variable known to me currently only as 'b', and I want to get to know you better."

Thankfully, our little 'b' variable is down to reflect on itself and tell you the result:

```
>>> type(b)
<class 'stripe.api_resources.balance.Balance'>
```

OK.  Its a custom class object.  You think to yourself. "OK, the documentation only gives me JSON, so since its not really a JSON formatted string like the docs lead us into thinking - we just confirmed this via the 'instanceof' call, and by explicitly asking the object what its type is - that must just be just what is printed to the console for the objects representation, and so it must be used internally in python code itself like an object, because it says it is one, right?" and you do this to test:

```
>>> hasattr(b, 'livemode')
True
```

OK.  You see it has the field as an object field, So you try to use it like an object:

```
>>> b.livemode
False

>>> hasattr(b, 'available')
True
```

Success.  Now we are getting somewhere, you think.  And since you found some success on this result value access,  you now think to yourself "Oh good, I'm in the clear, right? I can just treat it as an object with fields that match the docs JSON representation from now on, since even if the docs only give me the JSON representation of the object, I just need to mentally translate it from json to a class object with the same schema.  Sure, it increases the cognitive load a little, but I can do this. I know the schema now." you think to yourself.

Nope, Again a gap exists between the incomplete docs and the not-very python friendly stripe python API because the expectation in python is different than other languages:

```
>>> hasattr(b, 'available')
True

>>> b.available
[<StripeObject at 0x4969570> JSON: {
  "amount": 0,
  "currency": "usd",
  "source_types": {
    "card": 0
  }
}]
```

OK, so its a list of custom objects,  not the array of python value you expected from the docs, or even the more pythonic dict we might have been expecting in this specific case since this is Python, and ISO Currency standards dictate that currency type names are all unique and so a dict makes perfect sense here.  OK, It's just not optimized.  The world didn't end.  But it is still an object, right? After all, the object name is "Stripe**Object**" and it has a custom object name for its type, so we can use it like one every time, right?

Nope. Its just a StripeObject wrapped in its own type to make you feel good.  Its disguised.

![itsmydisguise](https://user-images.githubusercontent.com/569341/53854440-553cfc00-3f7e-11e9-8038-7b22fe3365c0.gif)

In fact, the error explicitly states that 'available' is a python list object of StripeObject's.  Wait, a python list? For an object that declares itself an object with named unique field values? Yes, that's what the '[' and ']' are for in the above output, and per even the docs - and yes the docs do show this - its a collection of objects to support multiple currencies each identified by what looks like their ISO 4217 alphabetic code values, even if this is not explicitly stated.

So that sort of makes sense if you switch your mental context outside of python and into JSON...  and also forget that ISO 4217 is all about making sure you have a unique primary key for different international currencies.  ಠ_ಠ

Per the Zen of Python (PEP20) at https://www.python.org/dev/peps/pep-0020/

> Explicit is better than implicit.

Taking a deep breath to ease the raising anxiety you may now feel at primary unique keys being possibly duplicated and needing to be tested for in thousands of different peoples code that may just only care about one currency, and just to test and confirm its not using overloaded dict semantics like we really want, we try the following:

```
>>> b.available.get('amount', 0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'list' object has no attribute 'get'
```

Ok. That confirms it.  So it really is a list object and not a dict in any way despite the clear opportunities presented by unique keys here.

Again: ಠ_ಠ

You might sigh here and think to yourself that its is not perfect, but it is implicitly documented by the json output that is the only documentation really provided for the object. But its very clear the language specific bindings are just not using the language specific features, and have a API design that opens the door to defects in code that consumes it, since you can't use an ISO 4217 key such as the alphabetic code 'USD' or the numeric code 840 to get your data you want, and you have to iterate to find things and do that work to populate a dict yourself... but you can use it if you do that.

Every time.

In every code base that only cares about one single currency.

![requiressomeeffort](https://user-images.githubusercontent.com/569341/53854929-51aa7480-3f80-11e9-98d3-ea6119135710.gif)


So if you think about it, you will really dislike the idea of all that repeated and duplicated effort in thousands, if not millions of peoples code, when clearly a central library is the perfect place to do that work once and only once, instead of forcing thousands of people to handle the same use case with different code... so shouldn't the option exist?

And this is just one single call, in only one of the API's that has this issue, that could be improved to provide better usability and a higher quality interface for the code that consumes it.

Finally, you think to yourself:

"Weird flex, but ok."
![oddflexok](https://user-images.githubusercontent.com/569341/53852873-54a16700-3f78-11e9-9c56-4d27dbeefa91.gif)

..as you try:

```
>>> b.available[0].get('amount', 'ಠ_ಠ')
1.00
```

Ok.  Not what we expected originally, but it works. Lets just hope its the correct currency you read in.  Wait, what currency is that for?  We are American so it should be in USD, right?

Maybe.

![possability](https://user-images.githubusercontent.com/569341/53854688-4acf3200-3f7f-11e9-8b15-df73188beeee.gif)


## Summery

API should be explicit and not implicit; The general feel of this code doesn't seem to denote an investment in the language or community it is supposed to represent to me, because its not following the rules of the language or the community itself, per the above reference to PEP20.

The documentation alone should be actively attempting to provide a working functional example past the initial network call and show how to actually use that result object explicitly, to at least get the data into a value the developer can then choose to use how they see fit or print to the console, but the docs get hand wavy because the choice was made to punt on the issue and not actually provide a python friendly API, merely a python usable one.

Putting aside blame, its a team effort and the team failed.

![collectiveeffort](https://user-images.githubusercontent.com/569341/53855496-c8e10800-3f82-11e9-830c-9a51292c564f.gif)

In the end, we should all be watching each others backs for things like this since money is involved, and that is exactly why I put so much effort into this post.

![thiscouldnotbelessimportant](https://user-images.githubusercontent.com/569341/53855664-7b18cf80-3f83-11e9-9603-3375142e157f.gif)

Yes a work around for OP's issue exists: Serialize the entire object to a json string, then read that resulting string out to a python object via a expensive and slow json,dumps/json.loads cycle... but should we really be doing this? 

![batmansaysno](https://user-images.githubusercontent.com/569341/53855745-d3e86800-3f83-11e9-831f-0e3b790695e8.gif)

Batman says no.. and so should you.

Its clearly not optimal, and not at all pythonic.  And while we could get into a really friendly and informative debate about pythonic verses non-pythonic code for the Python API's, the fact remains that the goal here is to easily extract values out of these result objects we get passed from the Stripe service.

So shouldn't the stripe library just give us python friendly result objects we can actually use in our code directly?  Or at least provide a language constant way to do so?


![yesrepeating](https://user-images.githubusercontent.com/569341/53855916-8c161080-3f84-11e9-94cc-4aef00b92696.gif)

**Comment by brandur-stripe** [comment]
@duaneking 

I hope this representation is fair, but I'd roughly summarize your objections as twofold:

1. It's not obvious that Stripe objects should have their properties accessed in dot style like `balance.livemode`.
    1. This confusion is partly because when inspecting objects, their string representation doesn't fully identify them with a complete name like `stripe.api_resources.balance.Balance` and spits out a JSON form of their properties.
    2. This confusion is also caused by underdocumentation on how to use a returned object once you have one.
2. Access in some places isn't convenient like trying to get a single currency from `balance.available`.

(1) is quite reasonable to address. For (1a), we could change the string representation to return a complete name and format returned properties instead of just showing JSON. For (1b), it might be a little difficult to get traction on adding returned object usage to every API ref/doc example, but it'd be quite plausible to put this in the README under a section like "how to use Stripe objects" and update other examples in there where it might be helpful.

We're unlikely to change anything for (2). Two points here:

* We try to have our API libraries map as closely as possible to what's actually in the web API. This helps establish useful symmetry between what you're seeing in the web API versus what you're doing in a language-specific API, but it also encourages good design in the web API and maximizes our flexibility for future changes in the web API.
* Regarding changing `available` from an array to a map: a map might be strictly more useful in your particular case, but it's not in general. One upside of the array is discoverability: you get a currency back in a field named `currency` instead of as an unnamed map key. Either if you don't find this convincing, we try to establish a single convention for this type of thing (say returning lists of currencies) and stick with it as widely as we can.

That's not to say that you shouldn't write your own layer of utility helpers on top of stripe-python if you find them useful (and we'd even encourage them). In the case of your single currency, imagine a simple function that gets the first element of a given array and errors with a useful debugging message if there was more than one. This isn't much additional imposition on developers like yourself because the functions are very simple to write, but it also doesn't add additional limitations and complications directly in stripe-python for more elaborate use cases like integrations that are handling multiple currencies.

**Comment by duaneking** [comment]
Why not just add these "helpful utility methods" to the actual stripe library so that people are not forced to repeatably reinvent the wheel?

**Comment by brandur-stripe** [comment]
> Why not just add these "helpful utility methods" to the actual stripe library so that people are not forced to repeatably reinvent the wheel?

Because they're not universally (or even mostly) appropriate. As in the example above, your integration may be handling only a single currency, but many aren't.

I should also note that this is a good example of where DRY is not a paramount value: if a function is simple enough, it's often better just to vendor it into your own code so that it's easy to see and understand the implementation, and have easy access to change it if need be.

**Comment by duaneking** [comment]
I do feel the code is too wet/needs to be more DRY, yes.  But that is not my real core point.  Its a side issue. I just cant help but feel like stripe cared more about printing out the objects as json than actually making them useful or usable, or providing working documentation, because we shouldn't have to hunt and peck at a debugger to figure out how to use that result object, either.

Since, after all, there is literally no documentation that shows otherwise.

I understand that many people do care about multiple currencies and thats a great example,  but I don't want is to get distracted on that; That specific singular issue is just a symptom of a greater issue here that boils down to PEP20 not being respected in the library design, and as a result its a lot more work to work with than it should be due to these issues that make it harder to consume and work with; And that creates lower quantity code and puts stripe and its customers at risk in the worst case.

I'm nit against minimalism in code; I enjoy minimal and elegant code.. But code also exists to be functional and when the company shipping code doesn't believe in that code enough to document it despite what is clearly at stake, how am I supposed to trust it?

**Comment by rattrayalex-stripe** [comment]
Hi @duaneking , 

Would you mind amending a few of your comments to be a bit more considerate? The original authors of stripe-python are nice people and meant well in their implementation, even if Python was not their first tongue. I'm not sure they'd feel great if they read some of these comments.

I know you mean well, too – "Do No Harm" is in your profile, after all, and you clearly just want a good python library for everybody. Much support for that.

Suggestions like taking a closer look at PEP20, and documenting things a bit more richly, are good ideas, and we're happy to consider them!

Cheers,
Alex

**Comment by duaneking** [comment]
@alex-stripe  I’m not sure what you mean when you say the time and effort I have put into this is not considerate,   I even added memes and jokes to lighten the tone, but I would be happy to take a look at something if it’s explicitly called out as I am very confused by your statements.

I put a lot of effort into trying to make sure that I was as considerate as possible while still being forthright and honest about the issues; if I missed something email me or contact me on Twitter and we can work it out.

**Comment by brandur-stripe** [comment]
> I understand that many people do care about multiple currencies and thats a great example, but I don't want is to get distracted on that; That specific singular issue is just a symptom of a greater issue here that boils down to PEP20 not being respected in the library design

Just to rollback a little ways: we're interested in fixing anything that would help with the library's usability, but to do that we need to generate a list of specific, actionable items. That's why I assembled the summary and list above — to start making materializing any concrete asks that we can. You've mentioned PEP 20 quite a few times. It's a fun, light-hearted document containing vague wisdom materialized as list of aphorisms. It's an interesting read for sure, but by definition subjective, and referencing it isn't going to help get any work done.

The reason I brought up the single currency helper is to note that it's a specific example of a class of change that we're not going to make (the justification for that hopefully being clear above), but that doesn't mean we can't make others.

I'll re-propose my original list above of possible improvements based on some ideas put forward in your original text:

1. Make string representations of Stripe objects more useful.
2. Add more usage clarity in the README.

If you've got any others, let us know, but please mind the constraints above. Thanks!
