### ISSUE TITLE
stripe 1.33.0

### ISSUE THREAD

**Issue by papachoco** [stripe/stripe-python#228]
Hello,

Could you provide with a sdist (egg) for stripe 1.33.0 in PyPI. The egg/source cannot be found / install using easy-install

Thanks

Carlos

**Comment by olivierbellone** [comment]
Hey Carlos,

The `stripe-1.33.0.tar.gz` package available on PyPI is actually a sdist: https://pypi.python.org/pypi/stripe/1.33.0.

Eggs are deprecated and have been replaced by wheels, but if you need to, you can build an egg from the source yourself: `python setup.py bdist_egg` will work.

Although `easy_install` is also deprecated and `pip` should be preferred, you should still be able to use it to install the `stripe` package: `easy_install stripe` should work.

I'll close the issue but feel free to reopen with additional details if this doesn't work for you.

**Comment by olivierbellone** [comment]
Reopening because I just noticed that the wheels for Python 2 and 3 have not been uploaded to PyPI for version 1.33.0. This isn't a huge issue -- I think `easy_install` and `pip` will just fall back to using the sdist. Nevertheless, we should fix this.

cc @stripe/api-libraries, can someone with PyPI access rebuild the wheels and make sure they're uploaded?

**Comment by brandur** [comment]
Hey, sorry about the unresponsiveness here!

I've just released 1.34.0 because we had a fix/addition sitting in master anyway. I think the PyPi uploads went through successfully this time. Let me know if you see anymore problems. Thanks!
