### ISSUE TITLE
exception json_body is not json?

### ISSUE THREAD

**Issue by robert-kisteleki** [stripe/stripe-python#239]
Hi,

When I capture a StripeError exception, and print the field json_body, I get something like:

`{'error': {'type': 'invalid_request_error', 'message': 'No such token: tok_18c...', 'param': 'source'}}`

That's **NOT** JSON, as JSON only allows double quotes. Hence trying o parse it with json.loads fails with "json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes".

Maybe that's not how it should work, maybe the field name is misleading? Or am I just confused?

**Comment by olivierbellone** [comment]
Hey @robert-kisteleki. `json_body` is already decoded -- it's a dict that's formed from the JSON text returned by the API. By default, Python use simple quotes to represent strings, which isn't compatible with JSON. If you wanted to recreate a JSON dump from the dict, you'd need to do something like `json.dumps(e.json_body)`.

**Comment by robert-kisteleki** [comment]
Right. So it seems the field name is misleading. Since the response body comes back in JSON, it would make sense that the field json_body contains precisely that :-)

**Comment by robert-kisteleki** [comment]
I'd suggest `json_body_raw` or such -- that way you preserve backwards compatibility (for users who depend on the current name/semantics). The raw field could just store whatever came back originally. This has the additional benefit to be authoritative in case the translation is wrong.

**Comment by brandur** [comment]
> I'd suggest json_body_raw or such -- that way you preserve backwards compatibility (for users who depend on the current name/semantics). The raw field could just store whatever came back originally. This has the additional benefit to be authoritative in case the translation is wrong.

Is there a reason you'd ever want to get access to the raw version though? I would have thought that the current behavior of decoding the body automatically would be most useful to users, even if someone ineptly named.

**Comment by robert-kisteleki** [comment]
I can't speak for others, but for me there's value in storing the whole answer as is. This way I can always look at it later, in case there's a discrepancy/dispute (which, in the payment context, is more interesting :-). I could cherry pick which fields I care about and only store those, but I never know if there's more (in a new version?) so I have to change my code.

I guess one could also pickle `json_body` but that would have a few drawbacks as well.

(BTW same goes for the success scenario -- there it's even more interesting to store all fields -- but that seems to be covered already.)

**Comment by brandur** [comment]
@robert-kisteleki Ah, interesting. Hm, I have to say that my intuition here is still to leave as is. You have a point that there may be some rational in storing the entire error response, but in the majority of cases it'll be vastly more useful to just store a response error type, message, and code (say for running analytics on the most common types of errors that you run into). 

Even where that's not the case, you're probably better off persisting the body as JSON instead of a string (i.e. into a Postgres jsonb field or a Mongo document), so `json_body` will still be more useful there.

Admittedly there are some cases of course (like your own) where none of the above is desirable, but for these I'd tentatively recommend just re-serializing what you see in `json_body`. There's some performance impact here, but hopefully your stack isn't seeing all that many errors back from Stripe, and dumping/loading JSON is one of the faster things that you can do in a Python stack.

**Comment by robert-kisteleki** [comment]
> Even where that's not the case, you're probably better off persisting the body as JSON instead of a string (i.e. into a Postgres jsonb field or a Mongo document), so json_body will still be more useful there.

That's kind of the point. In order to store as JSON, one needs JSON... That can be recreated from the de-jsonified version -- or using the response as is. There is a performance impact with parsing and rebuilding, which is of course possible today and not really a problem. But since the original version *is* available, this would be basically undoing what the parser does.

Let's cut to the chase: do you need a PR? :-)

**Comment by brandur** [comment]
> That's kind of the point. In order to store as JSON, one needs JSON... That can be recreated from the de-jsonified version -- or using the response as is. There is a performance impact with parsing and rebuilding, which is of course possible today and not really a problem. But since the original version is available, this would be basically undoing what the parser does.

Hm, I think much more likely in these cases is that you'll be using an interface to your data store that represents documents via Python arrays and dictionaries rather than encoding them as a string. [Here's what that would look like for jsonb with SQL Alchemy for example](https://www.compose.com/articles/using-json-extensions-in-postgresql-from-python-2/).

> Let's cut to the chase: do you need a PR? :-)

I hugely appreciate the offer, but let's leave as is for now. It's better to err on the side of not expanding the public interface if possible.

**Comment by robert-kisteleki** [comment]
Understood. Sorry for the noise!

**Comment by brandur** [comment]
No worries at all! I appreciate the discussion.
