### ISSUE TITLE
Using proxy with stripe-python

### ISSUE THREAD

**Issue by krassif** [stripe/stripe-python#240]
In our environment, different proxies are used for different network segments. Configuring proxy with HTTP_PROXY / HTTPS_PROXY environment variables for our back end process will for sure create problems.

Is there a programmatic way of specifying proxy to be used by python-stripe?

Thanks.

**Comment by olivierbellone** [comment]
Hey @krassif. Stripe's Python bindings can use different HTTP libraries. We recommend using `requests` if possible.

`requests` will automatically detect and use the `HTTP_PROXY` / `HTTPS_PROXY` environment variables: http://docs.python-requests.org/en/master/user/advanced/#proxies, so that's what I'd recommend.

If using the environment variables is not possible, then you'll have to modify the bindings themselves as we don't currently provide a way to set the proxy parameters programmatically. You'd need to modify [this call](https://github.com/stripe/stripe-python/blob/master/stripe/http_client.py#L98-L103) to add the `proxies` parameter.

**Comment by krassif** [comment]
Thanks for the prompt reply. Did as suggested - proxy dictionary ended passed in.
