### ISSUE TITLE
Docs need updated

### ISSUE THREAD

**Issue by alex-cory** [stripe/stripe-python#246]
Hey I wasn't sure where to put this, but in your docs, the `stripe.Token` object (useful to make sure a user doesn't add the same card twice) contains a `fingerprint` field, but the docs don't show that. 

### [Stripe Docs](https://stripe.com/docs/api/python#token_object)
![image](https://cloud.githubusercontent.com/assets/5455859/18451061/5ea1c83c-78ea-11e6-9fd2-6f6f198a28b0.png)

----------------

### Postman request test
![image](https://cloud.githubusercontent.com/assets/5455859/18451227/e3e597b2-78ea-11e6-99de-84f5c1c7aaae.png)

**Comment by remistr** [comment]
@alex-cory The `fingerprint` property is only available when you create the token with a secret API key and never with the publishable key. This was released in the API version [2014-10-07](https://stripe.com/docs/upgrades#2014-10-07):

> Publishable keys can no longer be used to retrieve token objects. When a card or bank account token is created with a publishable key, the fingerprint property is no longer included in the response.

Our example uses a Secret API key to crete and retrieve the token which is why you're seeing it in the docs.

**Comment by remistr** [comment]
Okay I completely misread your message and it was the complete opposite, sorry about that.

Thanks a lot for the report and I'll make sure this gets fixed in our documentation! In the future, I'd recommend emailing support directly for docs issues as this place should be limited to bug reports about our Python library!

**Comment by alex-cory** [comment]
Sorry about that! I'll make sure to do that! Just wasn't sure who exactly to let know. :)
