### ISSUE TITLE
KeyError 'id' - Can't get Account Ids...

### ISSUE THREAD

**Issue by NatuMyers** [stripe/stripe-python#261]
```
import stripe #is better practice because this lib does that anyways.
stripe.api_key = "sk_test_xyz"
....

            # create
            new_acct = stripe.Account.create(
              managed=True,
              country="US",
              email=request.POST['email'] 
            )

            profile.stripe_id = new_acct["id"]
            profile.stripe_keys_secret = new_acct["keys"]["secret"]
            profile.stripe_keys_publishable = new_acct["keys"]["publishable"]

```

Can't get them because of a key error.
 What gives?

<img width="725" alt="screen shot 2016-10-31 at 2 06 10 am" src="https://cloud.githubusercontent.com/assets/11301115/19845597/afa76af8-9f0e-11e6-920c-081320ed17a0.png">

I attempted to convert to a dict with similar results.

**Comment by ob-stripe** [comment]
Hey @NatuMyers. That's strange, I recommend you contact Stripe support directly: https://support.stripe.com/email and provide the request ID so that we can look at your account's logs and verify what the API replied with for this account creation request.

Could you also tell us which version of the Stripe Python library you're using? You can check this with:
```bash
python -c "import stripe; print(stripe.VERSION)"
```

Also:
- you should wrap all calls to Stripe's API in `try/catch` blocks (cf. https://stripe.com/docs/api/python#handling-errors)
- you don't need to save the publishable and secret keys. You can just create tokens using the platform's publishable key, and the tokens will be usable with any account that's connected to the platform. For other API requests, we recommend that you use the platform's secret key along with the [`Stripe-Account`]() header.

**Comment by NatuMyers** [comment]
Gotcha, will do.  python -c` "import stripe; print(stripe.VERSION)" `returned 1.41.1

**Comment by ob-stripe** [comment]
@NatuMyers One of my colleagues will reply with more information, but it looks like your requests are failing because you're using TLS 1.0 (cf. https://stripe.com/blog/upgrading-tls).

This is still a bit surprising because the account creation request should raise a `stripe.error.InvalidRequestError` in this case, so you must have something in your code that silences the exception (maybe a Django thing? I'm not terribly familiar with Django). But the correct answer here is what I mentioned above: you should wrap all your calls to Stripe's API in `try...except` clauses as I mentioned above, and not proceed if an exception is raised.
