### ISSUE TITLE
ResourceWarning unclosed ssl.SSLSocket

### ISSUE THREAD

**Issue by ChaosMTA** [stripe/stripe-python#313]
Everytime I use the stripe API to create a charge I get that resource warning. My implementation is pretty simple.

```python
                charge = stripe.Charge.create(
                    amount=amount*100,
                    currency=getattr(settings, 'CURRENCY'),
                    description=description,
                    source=token
                )
```
Results in:
```
E:\Development\users\views_purchase.py:147: ResourceWarning: unclosed <ssl.SSLSocket fd=1464, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.31.10.6', 51611), raddr=('54.187.208.163', 443)>
  source=token
```
![](http://i.imgur.com/FUGekxk.png)

**Comment by brandur-stripe** [comment]
@ChaosMTA Are you using Requests? I think it's this problem: https://github.com/kennethreitz/requests/issues/1882

It's being described as "annoying, but not a bug" because it's not so much of an indication of a problem as it is just a client that Requests was keeping open in case you made another requests, and which was disposed of without being explicitly closed.

You should be able to fix it by managing the lifetime of your own `Session` object like this:

``` python
from requests import sessions
session = sessions.Session()
client = stripe.http_client.RequestsClient(session=session)
stripe.default_http_client = client

# do work

session.close()
```

**Comment by ChaosMTA** [comment]
@brandur-stripe Thanks for the reply.

I am not explicitly using requests, just using whatever the Stripe API uses by default. Wouldn't it make sense for the Stripe API to close the session after I call it? Instead of having me do it in my code.

**Comment by brandur-stripe** [comment]
> I am not explicitly using requests, just using whatever the Stripe API uses by default. 

So we have kind of a fallback system so that we use Requests if it's available (we `import requests` and use it unless there was an error). So I guess the real question here is, is Requests available from your runtime? (I think it probably is.)

> Wouldn't it make sense for the Stripe API to close the session after I call it? Instead of having me do it in my code.

So if you take a look at that other thread, this really is a feature and not a bug. Establishing a new connection to Stripe has a few round trips worth of overhead and it's a common convention in HTTP to re-use a connection to avoid this initial cost of construction. By leaving that connection open, Requests is making your subsequent HTTP calls a little faster, which is a rational default.

If anything, this warning should probably be removed, because it's not actually something that will lead to a problem. If it's really bothering you though, you can get rid of it using something like the code above.

**Comment by ChaosMTA** [comment]
@brandur-stripe Thanks for the clarification!

I'll just ignore it :)
