### ISSUE TITLE
AttributeError : Unicode object has no attribute 'get'

### ISSUE THREAD

**Issue by VictorAny** [stripe/stripe-python#335]
I discovered this when following the OAuth example. Specifically during invocation of `stripe.OAuth.token(code, grant_type)`
 Occurs at `api_requestor.py", line 181, in specific_api_error`

`error_code=error_data.get('code'),`

I was able to confirm it wasn't an issue on my part by successfully sending a token via curl. 
Attempted encoding the returned code but the error continued to persist.

Python ver. -> 2.7.9
Stripe ver. -> 1.59.0

**Comment by VictorAny** [comment]
Seems after changing the api key to the secret key from the publishable key, the OAuth client code works. Seems like it would be good to show some sort of message for the error since it left me clueless.

**Comment by ob-stripe** [comment]
@VictorAny Sorry for ignoring this issue for so long!

I'm fairly sure the problem was because if you use an invalid key, the OAuth API returns `invalid_client` error. Previously, the library was unable to handle this error, but this has been fixed as of [1.63.0](https://github.com/stripe/stripe-python/blob/18579d9c28e36aaed0fb531e5ed4aacadb415b7f/CHANGELOG#L5-L7).

I have just tried the OAuth example with a publishable key and the latest version of the library (1.63.1) and the error is correctly handled. The following message is displayed:

> Error: Request ...: Publishable key sent, but only secret keys can be used

I'll close the issue now, but feel free to reply if you're still having trouble with this and I'll investigate further.
