### ISSUE TITLE
'Stripe no longer supports API requests made with TLS 1.0.'

### ISSUE THREAD

**Issue by prakashkumar163** [stripe/stripe-python#337]
I am getting this error in my local **window** .

'Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls.'

Please help

**Comment by ob-stripe** [comment]
@prakashkumar163 This error message is returned by the API, not by the Python library itself. You're seeing this error because your Python environment is using TLS 1.0 instead of TLS 1.2 to send requests to the API.

You can find some instructions to test your environment and upgrade it here: https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#python. If you still need help with this, you should write to support at https://support.stripe.com/email so that we can take a look at your logs and provide specific guidance.
