### ISSUE TITLE
Test-mode bank account creation when testing throws wrong error message

### ISSUE THREAD

**Issue by lajarre** [stripe/stripe-python#347]
Here is the procedure I followed when testing adding an external account to a Connect `Account` that was already created:

```
>>> my_account = stripe.Account.retrieve(...)
>>> my_account.external_accounts.create(external_account={
    'object': 'bank_account',
    'account_number': 'DE89370400440532013000',
    'country': 'FR',
    'currency': 'eur'
})
InvalidRequestError: Request ...: You cannot use a live bank account number when making transfers or debits in test mode
```

The `account_number` value comes from https://stripe.com/docs/connect/testing#creating-accounts

The solution was actually to change the `country` value to `DE` because the IBAN account number seemingly was German-style.

So it seems to me the error message is not precise enough here, which is a bit annoying since this kind of action (adding a bank account to an already created `Account` instance) is not well documented.

Or maybe I did things the wrong way?

Version: 1.65.1

**Comment by ob-stripe** [comment]
@lajarre Your code is fine. Note that you can also change the country code at the beginning of the test IBAN, e.g. you could use `FR89370400440532013000` if you wanted to add a bank account to a French connected account.

While your comment about the error message being unclear in this case is fair, it's not an issue with the Python library as the error is returned by the API and not by the library. Would you mind sending a message about this to support at https://support.stripe.com/email?

**Comment by lajarre** [comment]
Ok thanks for that. Will do!

**Comment by Hamza-falcon** [comment]
I am getting the same issue of Invalid bic and the above code did not work. 
StripeInvalidRequestError: Invalid bic
    at Function.generate

**Comment by paulasjes-stripe** [comment]
Hi @Hamza-falcon, this issues page is for bugs and problems with the library itself. Please reach out to Stripe support directly for integration issues: https://support.stripe.com/contact

**Comment by MohammadNaimDahee** [comment]
If you are receiving an "Invalid BIC" error when working with bank accounts in Stripe, it typically means that the BIC (Bank Identifier Code) you provided is either incorrect or not recognized by Stripe. Here are some steps to troubleshoot and resolve this issue:

Check the BIC: Verify that you have entered the correct BIC for the bank account. The BIC is an 8 or 11-character code used to identify financial institutions globally. Ensure that the BIC corresponds to the bank where the account is held.

Ensure Currency Compatibility: Confirm that the BIC is compatible with the currency you are specifying. Some banks have different BICs for different currencies. Make sure the BIC matches the currency you are using.

Use IBAN: In some cases, Stripe may require an IBAN (International Bank Account Number) instead of or in addition to the BIC, especially for European bank accounts. Ensure that you have the correct IBAN if it's required.

Check for Typographical Errors: Carefully review the BIC you have entered for any typographical errors. BICs are case-insensitive but should be accurate.

Bank Account Validation: Before adding a bank account to Stripe, it's a good practice to validate the bank account details with the user or through a third-party service to ensure the accuracy of the information.

Contact Stripe Support: If you have checked all the above steps and are still encountering the "Invalid BIC" error, consider reaching out to Stripe's support for assistance. They can help you troubleshoot and identify the specific issue.
