### ISSUE TITLE
Cannot Use .save() to Change Plans

### ISSUE THREAD

**Issue by zerox1212** [stripe/stripe-python#391]
Please clarify in the API docs that updating an active subscription using `sub.save()` will not upgrade or downgrade the subscription plan.

Example code:
```python
subscription = stripe.Subscription.retrieve('sub_49ty4767H20z6a')
subscription['items']['data'][0].plan.id = new_plan
subscription.save()
```

An API call must be initiated via `stripe.Subscription.modify()`. Using `save()` will only result in a call to `util.logger.debug("Trying to save already saved object %r", self)` and otherwise does nothing.

**Comment by remi-stripe** [comment]
@zerox1212 Which version of stripe-python are you currently using? I tried on my end that code and it works as expected and updates the first item's plan on the subscription but I tried on the latest version 1.77.1.

**Comment by ob-stripe** [comment]
Hi @zerox1212, that code wouldn't work as you cannot modify the list object under `items` in place. If you want to [update an existing subscription item](https://stripe.com/docs/api#update_subscription_item), you can do it like this:

```python
subscription = stripe.Subscription.retrieve('sub_49ty4767H20z6a')
item = subscription['items']['data'][0]
item.plan = 'new_plan'
item.save()
```

**Comment by zerox1212** [comment]
@ob-stripe I know you closed this issue but I still think this difference needs to be specified in the API docs. The current docs make it appear that my original code example would work, but that is not case. Thanks for the info.

**Comment by ob-stripe** [comment]
I don't disagree that this quirk should be documented somewhere, but I'm not sure what the best place would be. The issue is not specific to subscriptions (although subscriptions would probably be the most common usecase) and also I suspect not specific to Python -- it has to do with how our libraries handle updates on an attribute in a list object that's itself nested under another object. Basically the parent object does not know that an attribute was updated on the nested list object, and so calling `save()` on the parent object does nothing.

**Comment by zerox1212** [comment]
Based on that explanation it sounds like saving should probably be recursive. If it is found there is nothing to save in the root object you could traverse down the children until change is found and then saved. Until then there could be a note that calling save only works on the root object. Thanks for the explanation.
