### ISSUE TITLE
Stripe Timeout on App Engine Is Too Short When Being Called from TaskQueue

### ISSUE THREAD

**Issue by speedplane** [stripe/stripe-python#40]
Currently, on Google App Engine, the stripe client times out if a request takes more than 55 seconds.  The reason for this (see code below), is because Google App Engine has a 60 second timeout for normal requests.  However, App Engine backends and TaskQueues are not subject to this deadline.

It is a common usage scenario to do a lot of heavy lifting for billing on a backend (e.g., running reports, generating invoices, etc.).  Often the 55 second timeout is too short and the request times out.  

Please increase this timeout, or better yet, detect when running in a TaskQueue and increase it only in that situation.  Thank you.

stripe.__init__.py:427
```
    # GAE requests time out after 60 seconds, so make sure we leave
    # some time for the application to handle a slow Stripe
    args['deadline'] = 55
```

**Comment by kyleconroy** [comment]
Apologies for the slow response time here (again...). Since we haven't heard from anyone else in the last ~year, I'm going to assume this isn't a blocker for many app engine users. However, I still agree that this is a needed feature. We'll make sure to allow this timeout to configured when we add support for custom HTTP backends.

**Comment by kyleconroy** [comment]
And if this is still causing problems, you can now set your own deadline.

```python
import stripe
from stripe.http_client import UrlFetchClient

stripe.default_http_client = UrlFetchClient(deadline=70)
```
