### ISSUE TITLE
pip install stripe not working

### ISSUE THREAD

**Issue by daliu** [stripe/stripe-python#443]
Hey guys, I'm working with a virtualenv that's configured correctly for other python packages (have downloaded to test), but strangely I keep getting issues with stripe's package.

➤ pip install -U stripe
UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting stripe
  Using cached https://files.pythonhosted.org/packages/62/0e/d4437ba1611d7cc83256205c86203d0a74032ac5b3b539e5d8d58d0b4e61/stripe-1.84.2.tar.gz
...
Requirement not upgraded as not directly required...
Requirement not upgraded as not directly required...
...
Skipping bdist_wheel for stripe, due to binaries being disabled for it.
Installing collected packages: stripe
  Running setup.py install for stripe ... done
Successfully installed stripe

But then when I run my python version (same python version as pip), I'm getting module not found.
Might there be some check that's being missed? Do I need the bdist_wheel?

**Comment by ob-stripe** [comment]
Hi @daliu. This sounds like an issue with your specific Python environment rather than with the library. I would recommend reaching out to Stripe's support at https://support.stripe.com/email to describe the issue. Make sure to include information about your environment, such as which OS and version you're using, the exact Python, pip and virtualenv versions, etc.
