### ISSUE TITLE
Are stripe objects dicts?

### ISSUE THREAD

**Issue by oTree-org** [stripe/stripe-python#494]
When reading the docs about subscriptions, customers, etc., I sometimes see attribute notation, like 

```
subscription.tax_percent = 10
```

And sometimes see dict notation, like `subscription['items']['data'][0].id`, and sometimes see a mix (e.g. in the previous example why not use ['id'] at the end?)

What is the difference between the two? I was wondering if I could use dict notation all the way, like `subscription['items']['data'][0]['id']`. That means in my tests using `unittest.mock` I could patch the return values of `create`, `retrieve`, etc. using simple dict literals.

(By the way the docs have examples on how to use stripe-python, but I can't find any general explanation of how stripe-python is works, e.g. what data types it uses and how those map to JSON responses.)

Thanks!

**Comment by jleclanche** [comment]
stripe-python uses a custom dict object which supports lua/js-like behaviour of getting/setting keys through python attributes.

In dj-stripe we try to treat them purely as dict. It's more consistent.

**Comment by oTree-org** [comment]
Thanks!

**Comment by ob-stripe** [comment]
@oTree-org @jleclanche is correct, stripe-python's objects are indeed dicts with some additional magic to support dot notation.

The reason the documentation uses the `[]` notation when accessing `items` is that, because the objects are dicts, `subscription.items` returns the [`items()`](https://docs.python.org/3/library/stdtypes.html#dict.items) function rather than the value associated with the `'items'` key. So in this specific instance, using the dict notation is required.
