### ISSUE TITLE
Add API for checking zero-decimal currencies

### ISSUE THREAD

**Issue by jxltom** [stripe/stripe-python#508]
It will be nice to add an API or helper function to check if a currency is zero-decimal as documented in https://stripe.com/docs/currencies#zero-decimal. So we don't need to implement the lookup function from the table https://stripe.com/docs/currencies#presentment-currencies, which may be easily outdated.

**Comment by ob-stripe** [comment]
Hi @jxltom. GitHub issues are specifically for bugs or feature requests for Stripe's Python library, not for the backend API.

I'll pass your request along to the backend engineering team, though I'd suggest sending a message to support at https://support.stripe.com/email too so that we can follow up if needed.

**Comment by jxltom** [comment]
@ob-stripe Thanks! So this API or helper function does not exist neither in current python library or backend API, right?

**Comment by ob-stripe** [comment]
Yes, that's correct.

**Comment by jxltom** [comment]
Thanks!
