### ISSUE TITLE
False errors raised intermittently when charging a card for a Connected account

### ISSUE THREAD

**Issue by kareemcoding** [stripe/stripe-python#536]
When creating a charge, the error below will be raised once every 50 charges or so, even though nothing has changed in my code or the status of the connected account and later on they tried again and it worked.

`InvalidRequestError You cannot access the connected accounts of your platform's connected accounts.`

And I took a look at the log on my stripe dashboard and everything was fine, but the charge was never created, but the logs think it was. Below is the code that thew the error.
```python
try:
    charge = stripe.Charge.create(
        amount=payment.stripe_amount,
        currency=payment.currency,
        source=stripeToken,
        description=payment.charge_description,
        application_fee=fee,
        stripe_account=payment.company.account_id,
    )
    return render(request, 'pay/charge-successful.html', {'charge':charge})
except stripe.error.CardError as e:
    body = e.json_body
    error  = body.get('error', {})
    error = error['message']
    return render(request,'pay/charge-failed.html',{'reason':error})
```

The Stripe logs for the event

```
POST /v1/tokens
2019/02/22 03:08:34
Summary
ID req_xxx
Time 2019/02/22 03:08:34
Method POST
URL /v1/tokens
Status 200
IP address xxx.xxx.xxx.xxx
Version 2018-11-08
Source Mozilla/5.0 (Android 8.1.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0
Origin https://xxx.xxx
```

```
Request POST body
{
  "card": {
    "number": "************xxx",
    "cvc": "*********",
    "exp_month": "xx",
    "exp_year": "xx"
  },
  "guid": "NA",
  "muid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
  "sid": "xxxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxxxx",
  "payment_user_agent": "stripe.js/c08ea5de; stripe-js-v3/c08ea5de",
  "referrer": "https://xxx.xxx/xxx/",
  "key": "pk_live_xxxxxxxxxxxxxxxxxxxxxxxx"
}

```
```
Response body
{
  "id": "tok_xxxxxxxxxxxxxxxxxxxx",
  "object": "token",
  "card": {
    "id": "card_xxxxxxxxxxxxxxxxx",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "MasterCard",
    "country": "xx",
    "cvc_check": "unchecked",
    "dynamic_last4": null,
    "exp_month": x,
    "exp_year": xxxx,
    "funding": "credit",
    "last4": "xxxx",
    "metadata": {
    },
    "name": null,
    "tokenization_method": null
  },
  "client_ip": "xxx.xxx.xxx.xxx",
  "created": 1550804914,
  "livemode": true,
  "type": "card",
  "used": false
}
```

**Comment by ob-stripe** [comment]
Hi @kareemcoding. This error is returned when you send a request with an [OAuth access token](https://stripe.com/docs/connect/standard-accounts#token-request) as the API key and the [`Stripe-Account` header](https://stripe.com/docs/connect/authentication#stripe-account-header). You can use one or the other, but not both at the same time.

The logs you pasted are for the token creation request which takes place in the frontend, not the charge creation request triggered by your backend Python code. You won't be able to see the failed request in your logs because this particular error happens during the authentication phase and so the request is not associated with a particular Stripe account.

My guess is that a different piece of your code must be changing the global API key with `stripe.api_key = ...`. When using Connect with OAuth access tokens, it is recommended that you do not change the global API key and instead pass the access token on a per-request basis. With the `stripe` python module, this is done by passing the access token as the `api_key` named parameter in your requests.

**Comment by ob-stripe** [comment]
Closing the issue as this doesn't appear to be a bug with the library, but feel free to reply here or reach out to Stripe's support at https://support.stripe.com/email if you have any questions.

**Comment by kareemcoding** [comment]
Hi @ob-stripe thanks for getting back, annoyed that I missed that. Appreciate your help.
