### ISSUE TITLE
Stripe creating subscription on payment failure

### ISSUE THREAD

**Issue by RedixImpact** [stripe/stripe-python#545]
I’m sorry to complain and don’t really know the appropriate place for this to go but the “feature” mentioned in the title legitimately is just a headache for people. I’m assuming MOST people are using standard checkout forms to initialize a subscription and making the customer track down an invoice which won’t even trigger any webhooks is absolutely insane.

**Comment by remi-stripe** [comment]
@RedixImpact You should not need to track any event on your webhook endpoint and you can know, on creation, whether the subscription's first charge succeeded or not. If it did, you're all set and if it did not, you can have your customer enter new card details and pay that invoice instead of attempting to create a new subscription.

This is definitely a shift in the approach but it is important to address some related changes that are coming such as moving to `PaymentIntent` for Invoices and Subscriptions to better handle cases such as 3D Secure or other payment methods.

Issues on this repository should be limited to bugs with the library though so I'd recommend discussing it with our support team directly instead as they can help you better understand the changes. You can contact them here: https://support.stripe.com/contact
