### ISSUE TITLE
Feature Request: Add error code description to ErrorObject

### ISSUE THREAD

**Issue by dramirez-tc** [stripe/stripe-python#634]
We have cases where we need to expand the error code to include the error code descriptions, where are documented here:

https://stripe.com/docs/error-codes

We keep dictionary of the error code and their description in our server-side code base.  But, I worry that it would get out of sync.

Adding that to the SDK would be simple.  The ErrorObject.construct_from() func would need to grab it from the API response.  But, the API doesn't currently return the description.  So the API would need to be updated as well.

Is this something that you think would be valuable to add?  I certainly do.

**Comment by remi-stripe** [comment]
@dramirez-tc Thanks for providing detailed feedback! The reason we're not returning the description here is because those are what we consider "developer-facing errors". Those are error state a developer usually faces when they build their integration and hit common pitfalls they should protect against.

If we returned the description inline, it'd be too tempting to think you can show the message to your customer and most of those messages are tailored for you as the developer. For example if you refund a charge already refunded, the message is: 
> The charge you’re attempting to refund has already been refunded. Update the request to use the ID of a charge that has not been refunded.
It's here to warn you as a developer but you don't want your customer to see this.

To help make this easier though we're sharing a directly url to that error message in `doc_url` which you can load quickly to see its description.

Does that make sense?

**Comment by dramirez-tc** [comment]
Yes, that makes sense.  And thanks, for taking the time to detail the explanation.  I can take this to our product team.

Cheers, and have a great weekend!
