### ISSUE TITLE
Unpickled Stripe objects can't be updated

### ISSUE THREAD

**Issue by imankulov** [stripe/stripe-python#657]
It looks like unpickled Stripe objects can't interact properly with the Stripe API. Reproduced at least for the Customer object. Reproduced for the Python2.7 and Python3.8.

**Version info**

```python
>>> import sys
>>> import stripe
>>> stripe.version.VERSION
'2.48.0'
>>> sys.version_info
sys.version_info(major=3, minor=8, micro=1, releaselevel='final', serial=0)
```

**Everything works well with regular Stripe objects**

```python
>>> cc = stripe.Customer.retrieve(id='cus_xxxx')
>>> cc.description = 'foo'
>>> ok = cc.save()
>>> cc.save()
<Customer customer id=cus_xxxx> JSON: {
  "address": null,
  "balance": 0,
...
```

**Pickle + unpickle makes a customer object impossible to save**

```python
>>> import pickle
>>> cc2 = pickle.loads(pickle.dumps(cc))
>>> cc2.description = 'bar'
>>> cc2.save()
InvalidRequestError                       Traceback (most recent call last)
...
InvalidRequestError: Request req_xxxx: Received unknown parameters: object, created, currency, delinquent, discount, livemode, sources, subscriptions, tax_ids. Did you mean source, description, or tax_id_data?
```

**Comment by remi-stripe** [comment]
@imankulov We recommend using `modify()` instead of `save()`. The latter has been deprecated for while, it's just here for compatibility reasons. This would also solve this issue as when you clone the customer, our library is unable to know what changed internally versus the original version you fetched so it's sending every property back to the API.

Instead, do this:
```
stripe.customers.modify('cus_xxxx', description='bar')
```

**Comment by imankulov** [comment]
Thanks for clarifying, @remi-stripe 👍
