### ISSUE TITLE
Deletion during iteration fails

### ISSUE THREAD

**Issue by jayvdb** [stripe/stripe-python#671]
Python 3.8 and stripe 2.50

I have a script running on a test instance which deletes old data, with criteria `created`, and it regularly fails, but continues when re-started.  This occurs on all models I have attempted so far, and my guess it is the pagination.  I can do a complete fetch of the list of objects before beginning deletion, and it is reasonable to require some pre-fetching at some level.  Ideally it should be possible to ask the paginator to always be one page ahead of the record being emitted from the generator so this can not happen, and even default to this if it doesnt have significant perf implications, and I suspect it doesn't.

```py
delete <class 'djstripe.models.billing.Plan'> acct_1GW7fzHlqM9uH8UM {'created': {'lt': '1593993600'}}
Deleting Plan for acct_1GW7fzHlqM9uH8UM:
list_kwargs {'stripe_account': 'acct_1GW7fzHlqM9uH8UM', 'created': {'lt': '1593993600'}}
  id=plan_HIcUnkN0AnyVDg, pk=None (<Plan: id=plan_HIcUnkN0AnyVDg>)
  id=plan_HIcUjIxlNluhQe, pk=None (<Plan: id=plan_HIcUjIxlNluhQe>)
  id=plan_HIcTPG8yANf9ML, pk=None (<Plan: id=plan_HIcTPG8yANf9ML>)
  id=plan_HIcTfqs3uqo8Qq, pk=None (<Plan: id=plan_HIcTfqs3uqo8Qq>)
  id=plan_HIcTNXrD8izMUQ, pk=None (<Plan: id=plan_HIcTNXrD8izMUQ>)
  id=plan_HIcRNPUeR7WOok, pk=None (<Plan: id=plan_HIcRNPUeR7WOok>)
  id=plan_HIcR36hhEE09re, pk=None (<Plan: id=plan_HIcR36hhEE09re>)
  id=plan_HIcQ7395qtJpO3, pk=None (<Plan: id=plan_HIcQ7395qtJpO3>)
  id=plan_HIcQJyJu2sL8ho, pk=None (<Plan: id=plan_HIcQJyJu2sL8ho>)
  id=plan_HIcQn319nczaX0, pk=None (<Plan: id=plan_HIcQn319nczaX0>)
Traceback (most recent call last):
  File "..."
    for stripe_obj in model.api_list(**list_kwargs):
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/list_object.py", line 120, in auto_paging_iter
    page = page.next_page()
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/list_object.py", line 157, in next_page
    return self.list(
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/list_object.py", line 15, in list
    stripe_object = self._request(
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/list_object.py", line 80, in _request
    response, api_key = requestor.request(method_, url_, params, headers)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 122, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 373, in interpret_response
    self.handle_error_response(rbody, rcode, resp.data, rheaders)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 152, in handle_error_response
    raise err
stripe.error.InvalidRequestError: Request req_HQ7JuiqFh7u60d: No such plan: 'plan_HIcQn319nczaX0'
```

**Comment by remi-stripe** [comment]
@jayvdb If you delete the plans, you can't use on of the ids as the cursor for the next page which means you can't do auto-pagination while also deleting objects. Instead, you should just get the first page every time since you have deleted all the elements in the first page.

If  you get a page with plan_100 to plan_91 and you delete all of them, you would just get the first page again (without any `starting_after`) and you'd get plan_90 to plan 81, etc.

**Comment by jayvdb** [comment]
I cant believe this can not be solved neatly within the pagination.

> Instead, you should just get the first page every time since you have deleted all the elements in the first page.

I am not deleting all of the elements.  I explain what I am doing in the issue.

**Comment by remi-stripe** [comment]
@jayvdb Unfortunately, if you delete the last element in a page then we can not paginate to the next page since that cursor points to something that doesn't exist anymore. I just gave an example of deleting all objects to clarify the issue but this is true even if you only delete the last element on the page.

> I am not deleting all of the elements. I explain what I am doing in the issue.

The example you gave didn't really show what you are deleting or not deleting unfortunately. But you do need to take this into account. We do recommend that you don't delete while paginating, at least not while keeping track of the cursor you are at

**Comment by jayvdb** [comment]
> Unfortunately, if you delete the last element in a page then we can not paginate to the next page

Please re-read my comments above carefully.

**Comment by remi-stripe** [comment]
@jayvdb I did read your comments multiple times carefully. The problem only happens when you delete the last element on a page (or the first if you paginate backwards). The approach you outline of fetching a page earlier while you interact with the current one could work but it's not something we would implement in the library at the moment. We do recommend separating the deletion logic from the pagination logic instead.

**Comment by jayvdb** [comment]
> The problem only happens when you delete the last element on a page

I explicitly suggested not doing that.

" Ideally it should be possible to ask the paginator to always be one page ahead of the record being emitted from the generator so this can not happen"

i.e. when the generator is on the last item in the current page, before yielding it, fetch the next page.  This is basic pagination theory.

**Comment by richardm-stripe** [comment]
Hi @jayvdb,

It's possible for the caller to "lookahead" by a single element, with a pretty trivial wrapper around the iterator:
```python
# Wraps an iterator with behavior that "looks ahead"
# by a single element
def buffer_iterator(iterator):
    prev = next(iterator)
    while True:
        try:
            new = next(iterator)
            yield prev
            prev = new
        except StopIteration:
            yield prev
            break

# and I tested like this
import stripe
import os
stripe.api_key = os.environ['STRIPE_SECRET_KEY']
print(stripe.Product.list().data[0])
for i in range(4):
  stripe.Plan.create(interval="week", currency="usd", amount=300, product="prod_xxx")
plans = buffer_iterator(stripe.Plan.list(limit=3).auto_paging_iter())
for p in plans:
  print(p.id)
  p.delete()
```
And this will prevent trying to paginate on the deleted element.

I'm hesitant to add pagination options into the ListObject's iterator itself. The iterator we provide can capture the simplest case, but for advanced pagination needs the user should implement their own, because that way they have the most control.

**Comment by jayvdb** [comment]
Thank you.  I can accept if you don't want to implement it in the library, now that you have at least acknowledged/understood what was being proposed.

Perhaps a note could be added to the documentation of the ListObject /  iterator methods.
