### ISSUE TITLE
Feature Request: Allow setting of subscription billing_cycle_anchor when using Stripe Checkout

### ISSUE THREAD

**Issue by J2Pi** [stripe/stripe-python#674]
Stripe checkout is absolutely fantastic but we noticed that when we're creating a Stripe Session for checkout, we do not have the option to pass in a billing cycle anchor for the subscription_data.
https://stripe.com/docs/api/checkout/sessions/create

Confirmed by others here: https://stackoverflow.com/questions/63375270/how-can-i-set-the-billing-cycle-anchor-when-setting-up-a-subscription-using-a-ch

Can / will this be supported sometime in the near future?

We need our subscriptions to all align on a certain date but this is a deal breaker and we may have to use Stripe Elements instead.

**Comment by remi-stripe** [comment]
@J2Pi Thanks for reaching out. Github issues are limited to bugs with the stripe-python library itself. Since your ask is more a feature request about the API, I'm going to close the issue I hope it's okay.

To give a bit of context though, it's something we will likely support in the future. It hasn't been prioritized for now as we work on more impactful features such as coupon or tax support but it's on our radar. I'd recommend registering your interest by flagging to our support team directly: https://support.stripe.com/contact

**Comment by bhch** [comment]
@J2Pi Good news: this feature has been [added a couple of days ago](https://github.com/stripe/openapi/releases/tag/v314).

I was going through the Checkout docs and was pleasantly surprised to see this option there: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-billing_cycle_anchor
