### ISSUE TITLE
[Design] Are you using a code generator ? What about pydantic and HTTPX ?

### ISSUE THREAD

**Issue by FabriceSalvaire** [stripe/stripe-python#694]
I guess commits like "Codegen for openapi ..." means you are using a code generator which is not is the source ???

Maybe you should consider for a refactoring of this library:
* [Pydantic](https://pydantic-docs.helpmanual.io)
* [HTTPX](https://www.python-httpx.org) as a **requests** asyncio alternative

Also the code of `object_classes.py` could be replaced by a "registration" metaclass.

**Comment by remi-stripe** [comment]
@FabriceSalvaire Thanks for the feedback! We are automatically generating most of our client libraries (all but stripe-go) from our [openapi spec](https://github.com/stripe/openapi) today!

Adding type support is unfortunately not something we will do in the short term because of the way the library is built. Today it supports every API version which means that when you retrieve an API object the types depend on the API version associated with the API request and it makes some types conflict with each other (a property was a boolean and is now an enum for example). For a type system to work well, we'd need to have the stripe-python library pinned to a specific API Version which is something we're considering in the future!

Similarly, for async support, it requires dropping support for older Python versions which are still used a lot by our users. It would also require a re-design of the library which we would likely tie to core improvements such as the typing system you mentioned above!

I'm going to close this out since we already have other issues tracking those feature requests in https://github.com/stripe/stripe-python/issues/327 and https://github.com/stripe/stripe-python/issues/650 I hope it's okay!

**Comment by maxdeichmann** [comment]
@remi-stripe i just came across this and was wondering: how are you guys building python code from the openapi docs? Are you using the 'official' openai converter? (https://github.com/OpenAPITools/openapi-generator)

**Comment by remi-stripe** [comment]
@maxdeichmann We built our own codegen tooling internally. It parses our openapi spec files and then generates all our server-side libraries today! Unfortunately none of it is open sourced at the moment sorry.

**Comment by maxdeichmann** [comment]
> @maxdeichmann We built our own codegen tooling internally. It parses our openapi spec files and then generates all our server-side libraries today! Unfortunately none of it is open sourced at the moment sorry.

No worries, thanks for the info!
