### ISSUE TITLE
Feature Request: Please Add Type-hint

### ISSUE THREAD

**Issue by KeisukeNagakawa** [stripe/stripe-python#750]
Hi, is there any plan for adding type-hint for Stripe?
It's hard for new comer like me to write correct method or variable type without type-hints.

Thanks.

**Comment by remi-stripe** [comment]
@KeisukeNagakawa It's something we want to do in the future but no short term plans for this. Adding type hints will require typing most objects which in turns requiring "pinning" those objects to a specific version of our API, so that you have the right exact list of properties or parameters. This comes at a cost in ease of adoption of the library too and would require major reworks too

We know we will get to this in the future but it's not something we're working on at the moment unfortunately. I'm going to close as we already have https://github.com/stripe/stripe-python/issues/650 for this but thanks for the feedback, we definitely hear it!
