### ISSUE TITLE
Deleting object.metadata[key] doesn't work anymore

### ISSUE THREAD

**Issue by adrienverge** [stripe/stripe-python#753]
Python 3.10
stripe-python versions tested: 2.1.0, 2.20.0, 2.33.0, 2.63.0 (latest)
Stripe API 2020-08-27 (latest)

Hello,

Deleting customer metadata using `= None` or `del metadata[key]` does not work anymore. It used to work, as [this other issue](https://github.com/stripe/stripe-python/issues/596#issuecomment-518768234) suggests.

Strangely, all stripe-python versions tested (from 2.1.0 to 2.63.0) have the bug. This could show a change on the Stripe API, but this doesn't seem to be the case because using `curl` instead of the Python lib works (see examples below).

How to reproduce:
```python
customer = stripe.Customer.create(metadata={'a': 1, 'b': 2})
print(customer.metadata)
# {
#   "a": "1",
#   "b": "2"
# }
# → THIS IS NORMAL

customer.metadata['b'] = None
customer = stripe.Customer.modify(customer.id, metadata=customer.metadata)
print(customer.metadata)
# {
#   "a": "1",
#   "b": "2"
# }
# → EXPECTED VALUE: {"a": 1}

del customer.metadata['b']
customer = stripe.Customer.modify(customer.id, metadata=customer.metadata)
print(customer.metadata)
# {
#   "a": "1",
#   "b": "2"
# }
# → EXPECTED VALUE: {"a": 1}

customer = stripe.Customer.retrieve(customer.id)
print(customer.metadata)
# {
#   "a": "1",
#   "b": "2"
# }
# → EXPECTED VALUE: {"a": 1}

customer.metadata['b'] = ''
customer = stripe.Customer.modify(customer.id, metadata=customer.metadata)
# → FAILS WITH: ValueError: You cannot set b to an empty string. We interpret
# empty strings as None in requests.You may set {"a": "1", "b": "2"}.b = None to
# delete the property
```

However, using a raw HTTP request successfully removes `b` from `metadata`:
```shell
curl -u rk_test_…: 'https://api.stripe.com/v1/customers/cus_…' -d 'metadata[b]'=
```

**Comment by dcr-stripe** [comment]
Thanks for the report @adrienverge. 

I think I know what's going on here... previously the options outlined in https://github.com/stripe/stripe-python/issues/596 were:

1: 
```
stripe.PaymentIntent.modify('pi_deadbeef', metadata={'damage_deposit_amount': ''})
```

2:
```
pi.metadata['damage_deposit_amount'] = None
pi.save()
```

Notice that this uses a `save()` call instead of modify. The `save()` route still works today. However you're right that `del` does not work correctly with the `metadata` object when passing it as a param to a method other than save.


Working on a fix now!

**Comment by adrienverge** [comment]
Thanks for this detailed answer, which is really helpful to understand the problem :+1: :+1:

OK for `del`.

For `= None` + `modify()`, based on your answer I think I can write a workaround by cloning the metadata object before deleting keys.

However, in my opinion the way stripe-python handles metadata is not constitent and confusion-prone (i.e. I still see a "bug"):
- Either passing a `None` value in `modify()` should delete the field.
- Or passing a `None` value in `modify()` does nothing at all (like the Ruby lib), but in this case it should be allowed to set `original_metadata = ""` to delete the field. Currently it crashes.

  It shouldn't be required from developers to *know* that the `metadata` dict should be cloned before.

  Could this be easily handled on stripe-python side, by cloning metadata inside the lib?

**Comment by dcr-stripe** [comment]
> Or passing a None value in modify() does nothing at all (like the Ruby lib), but in this case it should be allowed to set original_metadata = "" to delete the field. Currently it crashes.

This is only happening because you're directly mutating the dict on customer. If you clone `customer.metadata` and then set a value there to be `=""`, `modify()` will work as expected. The crash happens at the mutation itself, not in the `modify()` call.

In general, treating the received Stripe objects as immutable is the way to go if you plan on using `modify()`. This is a known thorny part of our SDKs, but unfortunately making them all immutable in practice would require a breaking change. I agree it's not ideal in the interim.

**Comment by adrienverge** [comment]
OK, makes sense.

It's still confusing to be allowed to mutate the dict to `= None` (without an effect when calling `modify()`) but not being able to mutate it to `= ""` :wink:

**Comment by databasedav** [comment]
arrived here from attempting to do a `.modify(metadata=None)` and nothing happening, it's caused by the behavior of `stripe.api_requestor._api_encode` which removes keywords with a `None` value entirely, i think if `None` is provided, it should be changed to `''` automatically to make the api more ergonomic
