### ISSUE TITLE
Feature Request: only 1 customer object in list payment methods API / default field in PaymentMethod object

### ISSUE THREAD

**Issue by karmingc** [stripe/stripe-python#778]
Currently, the payment methods API has a customer field that can be expandable. However, if we call the list payment methods API and require some information about the customer, it will include the whole customer object for all payment methods. This payload increases significantly and seems redundant.

Are there any plans of including the customer object once, possibly outside of the PaymentMethod object?

The reason why I require the customer object is to find out which payment method is the default source. Currently, I need to call both the customer API and the list payment methods API, which are two requests at approximately ~200ms. 

Alternatively, would it possible to include a is_default in the PaymentMethod object?

**Comment by remi-stripe** [comment]
@karmingc We don't have plans to change something like this at the moment no. This would be a significant departure from the default Expand behaviour and would require moving many one-off properties to the `list` response which wouldn't be really scalable and explicit. It's true that it increases the payload when listing PaymentMethods but it's not really a huge difference even with 100 objects and shouldn't cause latency impact as we optimize this internally.

The "default source" concept has also been deprecated for over 3 years since it's not compatible with the PaymentMethods API. There's no concept of an "automatically set default payment method" today. What we have is the `invoice_settings[default_payment_method]` [property](https://stripe.com/docs/api/customers/update#update_customer-invoice_settings-default_payment_method) which you can set and use for Invoicing and Billing overall. If you set this one explicitly, you can expand it when you retrieve the Customer saving yourself an extra API request.

I'm going to close this out as github issues are limited to bugs with the library itself and this is more an integration question in the end or a feature request for the API itself which you can discuss with our support team here: https://support.stripe.com/contact

**Comment by karmingc** [comment]
@remi-stripe no worries, thanks for your reply - very insightful.
