### ISSUE TITLE
stripe.InvoiceItem.list issues

### ISSUE THREAD

**Issue by Mitch0S** [stripe/stripe-python#787]
Hello, when editing the example:

stripe.InvoiceItem.list(limit=3)

to 

stripe.InvoiceItem.list(limit=3, customer=customer_id)

or 

stripe.InvoiceItem.list(limit=3, invoice=invoice_id)

No InvoiceItems are retrieved, even though trying with the example returns the exact same data I'm trying to query...

**Comment by remi-stripe** [comment]
@Mitch0S I just tried locally and I can retrieve Invoice Items for a customer or an Invoice without issue with the library. It's unlikely to be an issue with the library itself at this point.

My guess would be that you pass the wrong ids for the customer or invoice, or that you're possibly mixing up the concept of an Invoice Item and an *Invoice Line Item* which are different. I'd recommend working directly with our support team for help here https://support.stripe.com/contact and you can also talk to developers on Discord here https://stripe.com/go/developer-chat otherwise
