### ISSUE TITLE
Gift Card API support

### ISSUE THREAD

**Issue by adlindenberg** [stripe/stripe-python#862]
We've gained access to the Gift Card beta and would like to use it but the latest tag of the stripe library (4.1.0b2) still says the `module 'stripe' has no attribute 'gift_cards'` when following Stripe's API examples [here](https://stripe.com/docs/api/gift_cards/cards/create?lang=python).

Is there planned support for this feature soon or only when it comes out of beta?

**Comment by remi-stripe** [comment]
@adlindenberg the official stripe-python library does not support beta features and would only have that API available once it gets out of beta unfortunately.

For the past few months though we have been working on "beta versions" of stripe-python and all the other libraries so that we can release beta features in them without impacting normal integrations. The GiftCards API is not yet in the beta branches but it's something we're looking into.

I'm going to tag your issue as "Future" for now while we work on this.

**Comment by adlindenberg** [comment]
Makes sense - we'll keep an eye out for it. Thank you for the feedback!

**Comment by ramya-stripe** [comment]
Thanks for your patience @adlindenberg 

We released support for the Gift Card API in version 4.2.0b2 of the python SDK over a month ago but missed updating you here.

You can use the latest beta version of the Python SDK which is 4.3.0b2 at the time of me writing this which will have the same support as well.
